---
name: "workflow"

'on':
  push:
    branches:
      - main
      - feat/equipo_1
    tags:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: "Integration"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@v2"
      - name: "Building Docker Image"
        run: |
          docker build -t equipo_1 nginx
      - name: "Lint code"
        run: |
          echo "Linting repository"
      - name: "Run unit tests"
        run: |
          echo "Running unit tests"
